\context ChordNames
	\chords {
		\set Score.markFormatter = #format-mark-box-numbers

		% intro
		\skip 1*4

		% Gloria a Dios en el cielo...
		\break
		\skip 1*4
		\skip 1*4

		% Te alabamos y te bendecimos...
		\break
		\skip 1*4
		\skip 1*4

		% Gloria a Dios en el cielo...
		\break
		\skip 1*4
		\skip 1*4

		% Solo tu eres santo...
		\break
		\skip 1*4
		\skip 1*4

		% La lara lala la la...
		\break
		\skip 1*4
		%\skip 1*2
	}
