\context DrumStaff = "Huevo"
<<
	\set Staff.instrumentName = "Huevo"
	\set Staff.shortInstrumentName = "H."
	\set Score.skipBars = ##t
	\set Staff.printKeyCancellation = ##f
	\drummode {

		%\override NoteHead #'stencil = #ly:text-interface::print
		%\override NoteHead #'text = #(markup #:musicglyph "scripts.stopped")

		r4-\mf  mar4 r2  |
		r4 mar4 r2  |
		r4 mar4 r2  |
		r4 mar4 r2  |
%% 5
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
%% 10
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4-\p  mar4 r mar4  |
		r4 mar4 r mar4  |
%% 15
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4-\mf  mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
%% 20
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
%% 25
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
%% 30
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
%% 35
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
%% 40
		r4 mar4 r mar4  |
		r4 mar4 r mar4  |
		mar1^^  |
		\bar "|."

	}
>>
